sonar.projectKey=sofia-tasklist-fronted
sonar.sources=src
sonar.tests=src/__tests__
sonar.test.inclusions=src/__tests__
# parce que j'ai oublié de mettre .tsx comme extension de test, c'est pour ça que le form marchait pas
sonar.typescript.lcov.reportPaths=coverage/lcov.info